FROM docker.elastic.co/kibana/kibana:7.9.2

# RUN apt-get update && apt-get install -y netcat
# COPY entrypoint.sh /tmp/entrypoint.sh
# RUN chmod 777 /tmp/entrypoint.sh

# COPY ./conf/kibana.yaml /opt/kibana/config/kibana.yaml

# CMD ["sh", "-c", "/tmp/entrypoint.sh"]