FROM docker.elastic.co/logstash/logstash:7.9.2

# add custom config
#COPY logstash.conf /config-dir/logstash.conf

# add templates
#COPY ./templates/ /config-dir/templates/
# ADD conf/logstash.conf /conf/logstash.conf